name: clair_db_update

on:
  workflow_dispatch: {}
  # Run every day at 5AM UTC
  schedule:
    - cron: "0 */6 * * *"

jobs:
  update_db:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Grab cache Clair DB
        uses: actions/cache@v4
        with:
          path: matcher.db
          key: matcher.db

      - name: Run Clair update DB
        uses: quay/clair-action@main
        with:
          db-file: matcher.db
          mode: update

      - name: update cache Clair DB
        uses: actions/cache@v4
        with:
          path: matcher.db
          key: matcher.db
